# -*- coding: utf-8 -*-
"""Netflix.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GudAUDCcfO7Up_JIs1dmkBAloLU2N6OG

# Netflix Analysis
"""


import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
sns.set_style
import warnings
warnings.filterwarnings('ignore')


df = pd.read_csv('netflix_titles.csv')
df.head()

"""#Understand the dataset"""

df.shape
df.info()

df.shape

"""There are 8807 observations and 12 variables"""

df.columns

df.describe()

df.describe(include='O')

df['type'].value_counts()

"""#Data Cleaning"""

df.isnull().sum()

"""## Missing Values Findings

The dataset contains missing values mainly in the columns "director", "cast", and "country". The "director" column has the highest number of missing values. Other columns such as "rating" and "date_added" have only a few missing entries.

This indicates that some information is incomplete, which is common in real-world datasets.
"""

df['date_added'] = pd.to_datetime(df['date_added'], errors='coerce')


df['date_added'].isnull().sum()


df['date_added'] = df['date_added'].fillna(df['date_added'].mode()[0])

df['date_added'] = pd.to_datetime(df['date_added'], errors='coerce')

df['director'] = df['director'].fillna('Unknown')
df['cast'] = df['cast'].fillna('Unknown')
df['country'] = df['country'].fillna(df['country'].mode()[0])
df['rating'] = df['rating'].fillna(df['rating'].mode()[0])

"""Duplicates"""

df.duplicated().sum()

df.isnull().sum()

df['duration'] = df['duration'].fillna(df['duration'].mode()[0])

"""## Data Cleaning

During the data cleaning process, missing values were identified and handled appropriately. Most columns were successfully cleaned, and only a small number of missing values remained in the "duration" column.

These values were handled using the most frequent value (mode), ensuring that the dataset remained complete without losing important information.

Additionally, the "date_added" column was converted into datetime format, and duplicate records were checked. Overall, the dataset is now clean and ready for analysis.

#Data Visualization

Content Type Distribution

This section analyzes the distribution of content types on Netflix, comparing movies and TV shows.
"""

plt.figure(figsize=(8,5))

sns.countplot(data=df, x='type', palette='Set2', edgecolor='black')

plt.title('Distribution of Movies and TV Shows', fontsize=16, fontweight='bold')
plt.xlabel('Type')
plt.ylabel('Count')

plt.show()

"""The visualization shows that Netflix has a significantly higher number of movies compared to TV shows. This suggests that the platform focuses more on movie content, although TV shows are also an important part of its catalog.

## Top Countries Producing Content

This analysis identifies the countries that produce the most content available on Netflix.
"""

plt.figure(figsize=(10,6))

df['country'].value_counts().head(10).plot(kind='bar')

plt.title('Top 10 Countries Producing Content', fontsize=16, fontweight='bold')
plt.xlabel('Country')
plt.ylabel('Count')

plt.xticks(rotation=45)

plt.show()

"""The United States is the leading producer of content on Netflix, followed by other countries. This highlights the strong dominance of U.S. productions on the platform.

## Content Ratings Distribution

This section examines the distribution of content ratings on Netflix to understand the target audience.
"""

plt.figure(figsize=(10,6))

sns.countplot(
    data=df,
    x='rating',
    order=df['rating'].value_counts().index,
    edgecolor='black'
)

plt.xticks(rotation=45)

plt.title('Distribution of Content Ratings', fontsize=16, fontweight='bold')

plt.show()

"""## Content Growth Over Time

This analysis explores how the number of titles added to Netflix has changed over time.
"""

df['year_added'] = df['date_added'].dt.year

plt.figure(figsize=(10,6))

df['year_added'].value_counts().sort_index().plot(kind='line', marker='o')

plt.title('Number of Titles Added Over Time')
plt.xlabel('Year')
plt.ylabel('Count')

plt.show()

"""## Top Content Genres

This section analyzes the most common genres available on Netflix.
"""

plt.figure(figsize=(10,6))

df['listed_in'].str.split(', ').explode().value_counts().head(10).plot(kind='bar')

plt.title('Top 10 Genres on Netflix', fontsize=16, fontweight='bold')
plt.xlabel('Genre')
plt.ylabel('Count')

plt.show()

"""## Content Type by Country

This analysis explores how movies and TV shows are distributed across countries.
"""

pd.crosstab(df['country'], df['type']).head(10)

"""## Ratings by Content Type

This section compares the distribution of ratings between movies and TV shows.
"""

plt.figure(figsize=(10,6))

sns.countplot(data=df, x='rating', hue='type')

plt.xticks(rotation=45)
plt.title('Ratings Distribution by Type', fontsize=16, fontweight='bold')

plt.show()

"""## Content Added by Month

This analysis examines whether Netflix adds more content during specific months.
"""

df['date_added'].dtype

df['month_added'] = df['date_added'].dt.month

plt.figure(figsize=(10,6))
sns.countplot(data=df, x='month_added')
plt.title('Content Added by Month', fontsize=16, fontweight='bold')
plt.xlabel('Month')
plt.ylabel('Count')
plt.show()

"""## Correlation Analysis

This section analyzes the correlation between numerical variables in the dataset.
"""

df['type_numeric'] = df['type'].map({'Movie': 0, 'TV Show': 1})

corr = df[['release_year', 'year_added', 'type_numeric']].corr()

plt.figure(figsize=(6,4))
sns.heatmap(corr, annot=True, cmap='coolwarm')

plt.title('Correlation Including Content Type')
plt.show()

"""## Correlation Analysis

The dataset shows weak correlations. Newer content is slightly more likely to be added to Netflix, but no strong relationships exist due to the categorical nature of the data.
"""

sns.scatterplot(
    data=df,
    x='release_year',
    y='year_added',
    hue='type',
    size='month_added',
    alpha=0.5
)

"""#The scatter plot

 Shows the time difference between a title’s release year and the year it was added to Netflix.

Most content is added within a few years after its release, indicating that Netflix focuses on relatively recent content. However, some titles take significantly longer to appear on the platform, suggesting that older content is also included.

Additionally, newer content tends to be added more quickly, which reflects Netflix’s strategy of keeping its catalog up to date.
"""
